Repository nsacyber/HIRS, pull requests merged in 2018-09, with the labels that each got.

#2 [#1] Add support for processing ECC certificates as part of the trust chain
  HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
Labels: bug, server

#5 [#3] Ensure ACA and TPM2 Provisioner handle versioning correctly
  .gitignore
  HIRS_AttestationCA/build.gradle
  HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
  HIRS_ProvisionerTPM2/CMakeLists.txt
  HIRS_ProvisionerTPM2/include/Version.h.in
  HIRS_ProvisionerTPM2/src/ProvisionerTpm2.proto
  HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp
  HIRS_Utils/src/main/java/hirs/data/persist/DeviceInfoReport.java
Labels: bug, client, server

#11 [#10] Fix representation of zero-valued hashes
  HIRS_Utils/src/main/java/hirs/data/persist/AbstractDigest.java
  HIRS_Utils/src/main/java/hirs/data/persist/Digest.java
  HIRS_Utils/src/test/java/hirs/data/persist/DigestTest.java
Labels: enhancement
