Repository nsacyber/HIRS, pull requests merged in 2019-03, with the labels that each got.

#114 [#24] Implementation of Component Class field
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
  HIRS_Utils/build.gradle
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentAddress.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentClass.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentIdentifier.java
  HIRS_Utils/src/main/resources/component-class.json
  HIRS_Utils/src/test/java/hirs/data/persist/certificate/attributes/ComponentClassTest.java
  HIRS_Utils/src/test/resources/config/component-class.json
  NOTICE
  build.gradle
  package/rpm/HIRS.spec
Labels: server

#101 [#95] Resolve Log4cplus Error complaining about no appenders
  HIRS_ProvisionerTPM2/include/Logger.h
  HIRS_ProvisionerTPM2/src/Logger.cpp
Labels: bug, client

#116 [#61] Remove Magic String Usage from PersistenceConfiguration
  HIRS_Utils/src/main/java/hirs/persist/DeviceHealthManagerImpl.java
  HIRS_Utils/src/main/java/hirs/persist/PersistenceConfiguration.java
  HIRS_Utils/src/test/java/hirs/persist/DeviceHealthManagerImplTest.java
Labels: refactor

#118 [#18] Add in Null Checks for Certificate and Subclasses
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
Labels: refactor

#117 [#115] Update System Platform Information for EK and Attribute Certs
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
Labels: server
