Repository nsacyber/HIRS, pull requests merged in 2019-05, with the labels that each got.

#129 [#111] ACA UI updates for V2 platform certificates
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/Page.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/index.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/platform-credentials.jsp
  HIRS_AttestationCAPortal/src/main/webapp/common/certificate_details.css
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/PlatformConfiguration.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/PlatformConfigurationV1.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/PlatformConfigurationV2.java
  HIRS_Utils/src/main/java/hirs/persist/CertificateSelector.java
  HIRS_Utils/src/test/java/hirs/data/persist/certificate/PlatformCredentialTest.java
  HIRS_Utils/src/test/resources/validation/platform_credentials/plat_base_cert1.pem
  HIRS_Utils/src/test/resources/validation/platform_credentials/plat_delta_cert1.pem
Labels: enhancement, server

#128 Attribute Validation Match Update
  HIRS_Utils/src/main/java/hirs/data/persist/ComponentInfo.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentIdentifier.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/AttributeStatus.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/ComponentIdentifierV2.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/V2/PlatformPropertyV2.java
  HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
  HIRS_Utils/src/test/java/hirs/data/persist/certificate/PlatformCredentialTest.java
  HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
Labels: server

#136 [#135] Fix DeviceInfoCollector's handling of C-Style Strings
  HIRS_Utils/src/main/java/hirs/client/collector/DeviceInfoCollector.java
Labels: bug, client

#137 [#135] tpm_version prints output containing nulls.
  HIRS_ProvisionerTPM2/src/tpm_version.cpp
Labels: bug, client

#140 [#139] Remove Maintainer Tags from Dockerfiles
  .ci/docker/Dockerfile.aca
  .ci/docker/Dockerfile.amazonlinux2
  .ci/docker/Dockerfile.centos7
  .ci/docker/Dockerfile.tpm2provisioner
  .ci/docker/Dockerfile.tpmprovisioner
  .ci/docker/Dockerfile.ubuntu18
Labels: documentation, refactor, testing

#147 [#146] Updated the jsp to correct the comment tags for content and jsp tag.
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
Labels: bug

#145 [#144] Rename integration-tests folder to setup under .ci directory
  .ci/docker/docker-compose-tpm2.yml
  .ci/docker/docker-compose.yml
  .ci/setup/certs/ca.crt
  .ci/setup/certs/ca.key
  .ci/setup/certs/ek_cert.der
  .ci/setup/setup-aca.sh
  .ci/setup/setup-tpm2provisioner.sh
  .ci/setup/setup-tpmprovisioner.sh
  .ci/system-tests/system_test.py
Labels: refactor
