Repository nsacyber/HIRS, pull requests merged in 2020-07, with the labels that each got.

#277 [#274] Swid Resource Not Found
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
  HIRS_Utils/src/main/java/hirs/data/persist/SwidResource.java
Labels: server

#288 [#287] removed unmappable characters from comment lines
  HIRS_Utils/src/main/java/hirs/tpm/eventlog/events/EvEfiBootServicesApp.java
Labels: bug

#291 [#290] RIM Upload modification
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
  HIRS_Utils/src/main/java/hirs/data/persist/ReferenceManifest.java
Labels: bug, enhancement, server

#289 [#282] ACA Firmware Validation 500 External error resolution
  HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/IssuedCertificatesPageControllerTest.java
  HIRS_ProvisionerTPM2/include/CommandTpm2.h
  HIRS_ProvisionerTPM2/src/CommandTpm2.cpp
  HIRS_ProvisionerTPM2/src/TPM2_Provisioner.cpp
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/IssuedAttestationCertificate.java
Labels: bug, enhancement
