Repository nsacyber/HIRS, pull requests merged in 2020-01, with the labels that each got.

#206 [#202] Certificate fail to save upon deletion during provisioning FIXED
  HIRS_AttestationCA/src/main/java/hirs/attestationca/CredentialManagementHelper.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateRequestPageController.java
  HIRS_Utils/src/main/java/hirs/data/persist/AbstractEntity.java
  HIRS_Utils/src/main/java/hirs/data/persist/ArchivableEntity.java
  HIRS_Utils/src/main/java/hirs/data/persist/Device.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/DeviceAssociatedCertificate.java
Labels: bug

#213 Update TPM 1.2 Provisioner docker image with latest tpm_module (v1.1.1)
  .ci/system-tests/system_test.py
Labels: enhancement, testing

#210 [#198] Reference Integrity Manifest Page List
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/Page.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/PageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/params/ReferenceManifestPageParams.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/persistence/PersistenceConfiguration.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/index.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/reference-manifests.jsp
  HIRS_Utils/src/main/java/hirs/data/persist/ReferenceManifest.java
  HIRS_Utils/src/main/java/hirs/persist/BaselineManager.java
  HIRS_Utils/src/main/java/hirs/persist/DBReferenceManifestManager.java
  HIRS_Utils/src/main/java/hirs/persist/PersistenceConfiguration.java
  HIRS_Utils/src/main/java/hirs/persist/ReferenceManifestManager.java
Labels: enhancement

#219 [#216] Upgrade docker images and system tests to support python3
  .ci/docker/Dockerfile.amazonlinux2
  .ci/docker/Dockerfile.centos7
  .ci/docker/Dockerfile.tpm2provisioner
  .ci/docker/Dockerfile.tpmprovisioner
  .ci/setup/addFaultyComponentsForPBaseCertB.py
  .ci/setup/createDeltaComponentsForPBaseCertA.py
  .ci/setup/createDeltaComponentsForPBaseCertB.py
  .ci/setup/setup-tpm2provisioner-base-delta-bad.sh
  .ci/setup/setup-tpm2provisioner-base-delta-good.sh
  .ci/setup/setup-tpm2provisioner.sh
  .ci/setup/setup-tpmprovisioner.sh
  .ci/system-tests/system_test.py
  .ci/system-tests/system_test_Driver.py
  .ci/system-tests/system_test_core.py
Labels: enhancement, testing
