Repository nsacyber/HIRS, pull requests merged in 2020-06, with the labels that each got.

#255 [#254] Modified how TPM2 Provisioner pulls down sub module cpr
  HIRS_ProvisionerTPM2/lib/CPR.CMakeLists.txt.in
Labels: bug

#256 [#251] tcg_eventog_tool packaging
  tools/tcg_eventlog_tool/build.gradle
  tools/tcg_eventlog_tool/libs/HIRS_Utils-1.1.1.jar
  tools/tcg_eventlog_tool/scripts/eventlog.sh
  tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Commander.java
  tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
Labels: client, enhancement

#263 Validation bug
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_Utils/src/main/java/hirs/data/persist/ArchivableEntity.java
  HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainValidation.java
  HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainValidationSummary.java
  HIRS_Utils/src/main/java/hirs/data/persist/TPMMeasurementRecord.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
Labels: bug

#272 [#266] Add Case statement for OID
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/PlatformCredential.java
Labels: bug

#271 [#265] IMA/TBoot PCR ignore policy
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/model/PolicyPageModel.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp
  HIRS_Utils/src/main/java/hirs/data/persist/ArchivableEntity.java
  HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java
  HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainPolicy.java
  HIRS_Utils/src/test/java/hirs/data/persist/PCRPolicyTest.java
Labels: enhancement
