Repository nsacyber/HIRS, pull requests merged in 2020-11, with the labels that each got.

#303 [#302] UEFI Refactor
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentClass.java
  HIRS_Utils/src/main/java/hirs/tpm/eventlog/uefi/UefiGuid.java
  HIRS_Utils/src/main/java/hirs/utils/JsonUtils.java
  HIRS_Utils/src/main/resources/vendor-table.json
  HIRS_Utils/src/test/java/hirs/tpm/eventlog/uefi/UefiProcessingTest.java
  HIRS_Utils/src/test/resources/tcgeventlog/uefi/vendor-table.json
  package/rpm/HIRS.spec
Labels: enhancement

#312 [#238] Client log mismatch display
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
  HIRS_AttestationCAPortal/src/main/webapp/common/rim_details.css
  HIRS_Utils/src/main/java/hirs/tpm/eventlog/TpmPcrEvent.java
Labels: enhancement, server

#313 Typing conflict when comparing event logs
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
  HIRS_Utils/src/main/java/hirs/utils/ReferenceManifestValidator.java
  tools/tcg_eventlog_tool/build.gradle
  tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
  tools/tcg_rim_tool/build.gradle
  tools/tcg_rim_tool/scripts/rimtool.sh
  tools/tcg_rim_tool/src/main/java/hirs/swid/CredentialParser.java
  tools/tcg_rim_tool/src/main/java/hirs/swid/Main.java
  tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagConstants.java
  tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagGateway.java
  tools/tcg_rim_tool/src/main/java/hirs/swid/SwidTagValidator.java
  tools/tcg_rim_tool/src/main/java/hirs/swid/utils/Commander.java
  tools/tcg_rim_tool/src/test/java/hirs/swid/TestSwidTagGateway.java
  tools/tcg_rim_tool/src/test/resources/keystore.jks
  tools/tcg_rim_tool/tcg_rim_tool.spec
Labels: bug, enhancement, testing

#315 [#314] Support RIM bug fixes
  HIRS_AttestationCA/src/main/java/hirs/attestationca/AbstractAttestationCertificateAuthority.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
Labels: bug, server

#317 [#316] Update component failure highlight
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/CertificateStringMapBuilder.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
  HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
Labels: refactor, server

#319 [#318] RIM upload error
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
Labels: bug, server
