Repository nsacyber/HIRS, pull requests merged in 2021-08, with the labels that each got.

#384 Updates to AttestationCA unit tests
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/service/SupplyChainValidationServiceImplTest.java
Labels: server, testing

#385 Update Portal servlet
  HIRS_AttestationCAPortal/build.gradle
Labels: bug, server, testing

#389 updated TCGEventLogEventsTest
  HIRS_Utils/src/test/java/hirs/tpm/eventlog/events/TCGEventLogEventsTest.java
Labels: testing

#388 Ignore tests from TPMBaselineGeneratorTest and ima.CSVGeneratorTest.
  HIRS_Utils/src/test/java/hirs/ima/CSVGeneratorTest.java
  HIRS_Utils/src/test/java/hirs/tpm/TPMBaselineGeneratorTest.java
Labels: testing

#390 Fixing one unit test revealed additional test updates.
  HIRS_Utils/src/test/java/hirs/appraiser/AppraiserPluginManagerTest.java
  HIRS_Utils/src/test/java/hirs/appraiser/TestAppraiserPlugin.java
  HIRS_Utils/src/test/java/hirs/data/persist/TPMBaselineTest.java
  HIRS_Utils/src/test/java/hirs/data/persist/TPMPolicyTest.java
  HIRS_Utils/src/test/java/hirs/data/persist/certificate/CertificateTest.java
  HIRS_Utils/src/test/java/hirs/persist/DBCertificateManagerTest.java
  HIRS_Utils/src/test/resources/certificates/stMicroCaCerts/stmtpmekint02.crt
Labels: bug, testing

#391 Fix for faulty logic in CertificateTest.testIsIssuer
  HIRS_Utils/src/test/java/hirs/data/persist/certificate/CertificateTest.java
Labels: testing

#394 Delta Component Unit Tests Fixes
  HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
  HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
  HIRS_Utils/src/test/resources/hirs/validation/sample_paccor_output.txt
Labels: testing
