Repository nsacyber/HIRS, pull requests merged in 2021-11, with the labels that each got.

#417 [#404] PXE Policy options
  HIRS_AttestationCA/src/main/java/hirs/attestationca/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/model/PolicyPageModel.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/policy.jsp
  HIRS_Utils/src/main/java/hirs/data/persist/PCRPolicy.java
  HIRS_Utils/src/main/java/hirs/data/persist/SupplyChainPolicy.java
Labels: bug, server

#420 RimLinkHash Fix
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
  HIRS_Utils/src/main/java/hirs/data/persist/BaseReferenceManifest.java
Labels: bug, server

#416 Vendor Table JSON refactor
  package/rpm/HIRS.spec
  tools/tcg_eventlog_tool/README.md
  tools/tcg_eventlog_tool/build.gradle
  tools/tcg_eventlog_tool/scripts/vendor-table.sh
Labels: bug, server, refactor

#415 [#414] Handle MODIFIED component without serial number
  HIRS_Utils/src/main/java/hirs/validation/SupplyChainCredentialValidator.java
Labels: enhancement, server
