Repository nsacyber/HIRS, pull requests merged in 2023-11, with the labels that each got.

#620 Update to the RIM Validator
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
Labels: enhancement

#617 Updated HIRS_Provisioner.NET package options
  HIRS_AttestationCAPortal/src/main/webapp/docs/HIRS .NET Provisioner Readme_2.2.pdf
  HIRS_Provisioner.NET/hirs.sln
  HIRS_Provisioner.NET/hirs/Directory.Build.targets
  HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
  HIRS_Provisioner.NET/hirsTest/hirsTest.csproj
Labels: bug

#619 Uploading Platform Credential IllegalStateException Fix
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
Labels: bug, server

#630 V3 server UI fixes
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/ArchivableEntity.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CACredentialRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CertificateRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/EndorsementCredentialRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/IssuedCertificateRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/PlatformCertificateRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
Labels: bug, server

#633 DB Returning non-null but blank Objects
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CertificateRepository.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
Labels: bug, server

#635 ACA Provisioning Clean up
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/ArchivableEntity.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/SupplyChainValidation.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/ComponentInfo.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/AbstractProcessor.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/helper/CredentialManagementHelper.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/ValidationService.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/SupplyChainCredentialValidator.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
Labels: bug, server
