Repository nsacyber/HIRS, pull requests merged in 2023-10, with the labels that each got.

#604 Add Ubuntu support for V3
  .ci/docker/Dockerfile.ubuntu22ci
  10
  HIRS_AttestationCAPortal/build.gradle
  package/scripts/aca/aca_check_setup.sh
  package/scripts/aca/aca_remove_setup.sh
  package/scripts/aca/aca_setup.sh
  package/scripts/db/db_create.sh
  package/scripts/db/db_drop.sh
  package/scripts/db/mysql_util.sh
  package/scripts/pki/pki_chain_gen.sh
  package/scripts/pki/pki_setup.sh
  test.sh
Labels: enhancement

#609 Creates a build/package action for V3
  .github/workflows/hirs_package_linux.yml
Labels: enhancement, testing, migration

#611 [#610] HIRS_Utils Unit Tests Migration
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentClassTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/TPMSecurityAssertionsTest.java
  HIRS_AttestationCA/src/test/resources/config/BasicTest.properties
  HIRS_AttestationCA/src/test/resources/config/Empty.properties
  HIRS_AttestationCA/src/test/resources/config/InvalidTPMCollector.properties
  HIRS_AttestationCA/src/test/resources/config/TestHIRSClient.properties
  HIRS_AttestationCA/src/test/resources/config/TestIMACollector.properties
  HIRS_AttestationCA/src/test/resources/config/TestMultipleAppraisers.properties
  HIRS_AttestationCA/src/test/resources/config/TestTPMCollector.properties
  HIRS_AttestationCA/src/test/resources/config/component-class.json
Labels: migration

#614 [#612] Migrate integration test for DevicePageController and associated classes
  HIRS_AttestationCAPortal/build.gradle
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/PageControllerTest.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/PageTestConfiguration.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/DevicePageControllerTest.java
  HIRS_AttestationCAPortal/src/test/resources/application-test.properties
  HIRS_AttestationCAPortal/src/test/resources/certificates/fakeCA.pem
  HIRS_AttestationCAPortal/src/test/resources/endorsement_credentials/ab21ccf2-tpmcert.pem
  HIRS_AttestationCAPortal/src/test/resources/endorsement_credentials/tpmcert.pem
  HIRS_AttestationCAPortal/src/test/resources/platform_credentials/Intel_pc.cer
Labels: migration
