Repository nsacyber/HIRS, pull requests merged in 2023-06, with the labels that each got.

#519 Updated ComponentClass TypeId equals
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/attributes/ComponentClass.java
Labels: bug, server

#518 [#502] Validation report download 500 error
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java
Labels: bug, server

#514 Dotnet hirs provisioner
  .ci/setup/appsettings.json
  .github/workflows/dotnet_provisioner_unit_tests.yml
  .gitignore
  HIRS_Provisioner.NET/.editorconfig
  HIRS_Provisioner.NET/hirs.sln
  HIRS_Provisioner.NET/hirs/Directory.Build.targets
  HIRS_Provisioner.NET/hirs/Resources/Product.wxs
  HIRS_Provisioner.NET/hirs/Resources/ProvisionerTpm2.proto
  HIRS_Provisioner.NET/hirs/appsettings.json
  HIRS_Provisioner.NET/hirs/hirs.csproj
  HIRS_Provisioner.NET/hirs/src/Program.cs
  HIRS_Provisioner.NET/hirs/src/client/Client.cs
  HIRS_Provisioner.NET/hirs/src/client/IHirsAcaClient.cs
  HIRS_Provisioner.NET/hirs/src/client/TbsWrapper.cs
  HIRS_Provisioner.NET/hirs/src/config/CLI.cs
  HIRS_Provisioner.NET/hirs/src/config/ClientExitCodes.cs
  HIRS_Provisioner.NET/hirs/src/config/Settings.cs
  HIRS_Provisioner.NET/hirs/src/deviceInfo/ClassicDeviceInfoCollector.cs
  HIRS_Provisioner.NET/hirs/src/deviceInfo/IHirsDeviceInfoCollector.cs
  HIRS_Provisioner.NET/hirs/src/provisioner/IHirsProvisioner.cs
  HIRS_Provisioner.NET/hirs/src/provisioner/Provisioner.cs
  HIRS_Provisioner.NET/hirs/src/tpm/CommandTpm.cs
  HIRS_Provisioner.NET/hirs/src/tpm/CommandTpmQuoteResponse.cs
  HIRS_Provisioner.NET/hirs/src/tpm/IHirsAcaTpm.cs
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/appsettings.json
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/component_list
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/cert/Mfg.Serial.BASE.cer
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/cert/platform/Mfg.Serial.ver2.base.cer
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/manifest/rim/Mfg.Model.1.rimel
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/manifest/rim/Mfg.Model.1.rimpcr
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/manifest/swidtag/Mfg.Model.1.swidtag
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.base.pem
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.delta.cer
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.rimel
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.rimpcr
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.swidtag
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/pccert/Mfg.Model.ver1.delta.pem
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/event_log
  HIRS_Provisioner.NET/hirsTest/hirsTest.csproj
  HIRS_Provisioner.NET/hirsTest/src/client/ClientTests.cs
  HIRS_Provisioner.NET/hirsTest/src/config/SettingsTests.cs
  HIRS_Provisioner.NET/hirsTest/src/provisioner/ProvisionerTests.cs
  HIRS_Provisioner.NET/tools/pcrextend/pcrextend.csproj
  HIRS_Provisioner.NET/tools/pcrextend/src/Program.cs
  HIRS_Provisioner.NET/tools/pcrextend/src/config/CLI.cs
  HIRS_Provisioner.NET/tools/pcrextend/src/tool/PcrExtendTool.cs
  HIRS_Provisioner.NET/tools/pcrextend/src/tpm/CommandTpmSimulator.cs
Labels: client, dotnet

#542 [#534] Fix for Downloading Certificates
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/platform-credentials.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/rim-details.jsp
Labels: bug, server, migration

#543 [#534] Updated display code
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CACredentialRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CertificateRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/EndorsementCredentialRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/IssuedCertificateRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/PlatformCertificateRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Certificate.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/PersistenceJPAConfig.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/datatables/OrderedListQueryDataTableAdapter.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
Labels: server, refactor, migration

#541 Filestore Service Removal
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/PersistenceConfiguration.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
Labels: server

#544 [#534] Base RIM Details Page
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/AbstractEntity.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentClass.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/BaseReferenceManifest.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/SupplyChainValidationServiceImpl.java
  HIRS_AttestationCA/src/main/resources/identity_transform.xslt
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/PersistenceJPAConfig.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_Utils/src/main/java/hirs/utils/BouncyCastleUtils.java
  HIRS_Utils/src/main/java/hirs/utils/SwidResource.java
  HIRS_Utils/src/main/java/hirs/utils/swid/SwidTagConstants.java
Labels: bug, migration
