Repository nsacyber/HIRS, pull requests merged in 2023-09, with the labels that each got.

#577 [#546] (Part 1) Migrating tests in /data/persist/ folder in HIRS_Utils
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/UserDefinedEntity.java
  HIRS_Utils/build.gradle
  HIRS_Utils/src/test/java/hirs/data/persist/FirmwareInfoTest.java
  HIRS_Utils/src/test/java/hirs/data/persist/HardwareInfoTest.java
  HIRS_Utils/src/test/java/hirs/data/persist/NetworkInfoTest.java
  HIRS_Utils/src/test/java/hirs/data/persist/OSInfoTest.java
  HIRS_Utils/src/test/java/hirs/data/persist/PolicyTest.java
  HIRS_Utils/src/test/java/hirs/data/persist/TestPolicy.java
Labels: testing

#574 [#560] Adds TLS to the hirs DB connector
  HIRS_AttestationCA/build.gradle
  HIRS_AttestationCAPortal/build.gradle
  HIRS_AttestationCAPortal/src/main/resources/application.properties
  HIRS_AttestationCAPortal/src/main/resources/hibernate.properties
  HIRS_AttestationCAPortal/src/main/resources/log4j2-spring.xml
  package/extras/aca/tomcat-mysql-hirs.pp
  package/extras/aca/tomcat-mysql-hirs.te
  package/scripts/aca/aca_bootRun.sh
  package/scripts/aca/aca_check_setup.sh
  package/scripts/aca/aca_remove_setup.sh
  package/scripts/aca/aca_setup.sh
  package/scripts/aca/certificate_generate.sh
  package/scripts/common/firewall_configure_tomcat.sh
  package/scripts/common/get_centos_major_version.sh
  package/scripts/common/get_db_service.sh
  package/scripts/common/jvm_version_check.sh
  package/scripts/common/my.cnf.el7
  package/scripts/common/secure_mysql.sql
  package/scripts/common/ssl_configure.sh
  package/scripts/common/ssl_deconfigure.sh
  package/scripts/db/db_create.sh
  package/scripts/db/db_create.sql
  package/scripts/db/db_drop.sh
  package/scripts/db/db_drop.sql
  package/scripts/db/start_mysqld.sh
  package/scripts/pki/pki_chain_gen.sh
  package/scripts/pki/pki_setup.sh
Labels: server, migration

#580 [#579] MISC ACA issues fixed
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Certificate.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentClass.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/CredentialHelper.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiGuid.java
  package/scripts/aca/aca_setup.sh
Labels: bug, enhancement, server

#595 Use protobuf-gradle-plugin to replace a system dependency
  HIRS_AttestationCA/build.gradle
Labels: enhancement
