Repository nsacyber/HIRS, pull requests merged in 2023-07, with the labels that each got.

#552 Reference Digest value UI Update
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceDigestValueRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceManifestRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/ReferenceDigestValue.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
Labels: bug, server, refactor

#558 [#550] Adds TLS to embedded tomcat
  HIRS_AttestationCAPortal/src/main/resources/application.properties
  HIRS_AttestationCAPortal/src/main/resources/log4j2-spring.xml
  package/scripts/aca/aca_bootRun.sh
  package/scripts/aca/aca_property_setup.sh
  package/scripts/aca/aca_setup.sh
  package/scripts/pki/.prop.file
  package/scripts/pki/ca.conf
  package/scripts/pki/pki_chain_gen.sh
  package/scripts/pki/pki_setup.sh
Labels: enhancement, refactor, migration

#557 [#546] Add TCGEventLogTest for main
  HIRS_Utils/build.gradle
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TCGEventLog.java
  HIRS_Utils/src/test/java/hirs/utils/tpm/eventlog/TCGEventLogTest.java
Labels: testing
