Repository nsacyber/HIRS, pull requests merged in 2023-08, with the labels that each got.

#561 Maven deployment of HIRS_Structs and HIRS_Utils
  HIRS_AttestationCA/build.gradle
  HIRS_AttestationCA/src/test/java/hirs/attestationca/IssuedCertificateAttributeHelperTest.java
  HIRS_AttestationCAPortal/build.gradle
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/datatables/package-info.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/model/package-info.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/package-info.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/package-info.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/package-info.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/params/package-info.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/persistence/package-info.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/util/package-info.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/package-info.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/datatables/package-info.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/package-info.java
  HIRS_Provisioner/build.gradle
  HIRS_Provisioner/src/main/java/hirs/provisioner/package-info.java
  HIRS_Structs/build.gradle
  HIRS_Structs/src/main/java/hirs/structs/converters/StructConverter.java
  HIRS_Utils/build.gradle
  HIRS_Utils/src/main/java/hirs/IMAReportRequest.java
  HIRS_Utils/src/main/java/hirs/ReportRequest.java
  HIRS_Utils/src/main/java/hirs/client/collector/DeviceInfoCollector.java
  HIRS_Utils/src/main/java/hirs/config/package-info.java
  HIRS_Utils/src/main/java/hirs/data/persist/AbstractEntity.java
  HIRS_Utils/src/main/java/hirs/data/persist/ArchivableEntity.java
  HIRS_Utils/src/main/java/hirs/data/persist/UserDefinedEntity.java
  HIRS_Utils/src/main/java/hirs/data/persist/baseline/Baseline.java
  HIRS_Utils/src/main/java/hirs/data/persist/baseline/IMABaselineRecord.java
  HIRS_Utils/src/main/java/hirs/data/persist/baseline/ImaBaseline.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/Certificate.java
  HIRS_Utils/src/main/java/hirs/data/persist/certificate/EndorsementCredential.java
  HIRS_Utils/src/main/java/hirs/ima/IMABaselineGeneratorException.java
  HIRS_Utils/src/main/java/hirs/package-info.java
  HIRS_Utils/src/main/java/hirs/persist/BaselineManager.java
  HIRS_Utils/src/main/java/hirs/persist/DBReportManager.java
  HIRS_Utils/src/main/java/hirs/persist/DBReportSummaryManager.java
  HIRS_Utils/src/main/java/hirs/persist/ReportManager.java
  HIRS_Utils/src/main/java/hirs/persist/ReportManagerException.java
  HIRS_Utils/src/main/java/hirs/persist/ReportSummaryManager.java
  HIRS_Utils/src/main/java/hirs/persist/ReportSummaryManagerException.java
  HIRS_Utils/src/main/java/hirs/repository/YumRepository.java
  HIRS_Utils/src/main/java/hirs/repository/spacewalk/SpacewalkChannelRepository.java
  HIRS_Utils/src/main/java/hirs/repository/spacewalk/SpacewalkService.java
  HIRS_Utils/src/main/java/hirs/tpm/TPMBaselineGeneratorException.java
  HIRS_Utils/src/test/java/hirs/DeviceGroupSerializerTest.java
  HIRS_Utils/src/test/java/hirs/ima/CSVGeneratorTest.java
  HIRS_Utils/src/test/java/hirs/repository/spacewalk/SpacewalkServiceTest.java
  HIRS_Utils/src/test/java/hirs/tpm/eventlog/TCGEventLogTest.java
  HIRS_Utils/src/test/java/hirs/utils/exec/ExecBuilderTest.java
  HIRS_Utils/src/test/java/hirs/validation/SupplyChainCredentialValidatorTest.java
  TPM_Utils/build.gradle
  TPM_Utils/src/main/java/hirs/tpm/tss/command/CommandTpm.java
  build.gradle
  config/checkstyle/sun_checks.xml
  gradle.properties
  tools/tcg_eventlog_tool/build.gradle
Labels: enhancement

#569 [#534] List Elements page fix
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/ReferenceDigestValueRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/DeviceAssociatedCertificate.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/DevicePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestDetailsPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/endorsement-key-credentials.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/issued-certificates.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/platform-credentials.jsp
  HIRS_Utils/src/main/java/hirs/utils/BouncyCastleUtils.java
Labels: bug, server

#571 updated github actions unit test yml, added Rocky 8.8 Dockerfile, resolves issue 570
  .ci/docker/Dockerfile.rocky88ci
  .github/workflows/hirs_unit_tests.yml
Labels: migration
