Repository nsacyber/HIRS, pull requests merged in 2024-02, with the labels that each got.

#695 Git ignore updates for the .NET provisioner
  .gitignore
Labels: bug, migration

#683 Bouncy Castle version update
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/EndorsementCredential.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/CommonCriteriaMeasures.java
  HIRS_Utils/src/test/java/hirs/utils/BouncyCastleUtilsTest.java
  settings.gradle
Labels: bug, enhancement, migration

#698 PCI Ids Translation Fix
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/PciIds.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/provision/helper/IssuedCertificateAttributeHelperTest.java
Labels: bug, server, migration

#688 [#684] Green Check mark fix
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/CACredentialRepository.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
Labels: bug, migration

#699 GitHub Workflow to create V3 ACA docker images and manifest
  .ci/docker/Dockerfile.aca-windows
  .github/workflows/build_aca_image.yml
  .github/workflows/create_aca_images.yml
Labels: enhancement, server

#702 [#643] Checkstyles implementation
  HIRS_AttestationCA/build.gradle
  HIRS_AttestationCAPortal/build.gradle
  HIRS_AttestationCAPortal/config/checkstyle/suppressions.xml
  HIRS_Structs/build.gradle
  HIRS_Structs/config/checkstyle/suppressions.xml
  HIRS_Utils/build.gradle
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiBootVariable.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiDevicePath.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiGuid.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiPartition.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureData.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiX509Cert.java
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  tools/tcg_eventlog_tool/build.gradle
  tools/tcg_eventlog_tool/config/checkstyle/suppressions.xml
  tools/tcg_rim_tool/build.gradle
Labels: migration

#701 Migrated 1 unit test to HIRS_AttestationCA
  HIRS_AttestationCA/build.gradle
  HIRS_AttestationCA/config/spotbugs/spotbugs-exclude.xml
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/AttestationCertificateAuthorityTest.java
  HIRS_AttestationCA/src/test/resources/tpm2/ak.name
  HIRS_AttestationCA/src/test/resources/tpm2/ak.pub
  HIRS_AttestationCA/src/test/resources/tpm2/ek.pub
Labels: migration

#711 V3 Update WiX
  HIRS_Provisioner.NET/hirs/Directory.Build.targets
  HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
Labels: bug, dotnet, migration

#712 V2 Update WiX
  HIRS_Provisioner.NET/hirs/Directory.Build.targets
  HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
Labels: bug, dotnet

#720 Migrated 1 unit test from master Utils to main HIRS_AttestationCA
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/AttestationCertificateAuthorityTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/AppraiserTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/tpm/TPM2ProvisionerStateTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/tpm/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/AbstractUserdefinedEntityTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/CertificateTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/DeviceTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/SupplyChainValidationSummaryTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/SupplyChainValidationTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/CertificateAuthorityCredentialTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/EndorsementCredentialTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/PlatformCredentialTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/TPMSecurityAssertionsTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/info/PortalInfoTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/info/TPMInfoTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/info/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/record/TPMMeasurementRecordTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/record/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/report/DeviceInfoReportTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/report/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/provision/helper/CredentialManagementHelperTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/provision/helper/IssuedCertificateAttributeHelperTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/provision/helper/package-info.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/validation/SupplyChainCredentialValidatorTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/validation/package-info.java
Labels: migration
