Repository nsacyber/HIRS, pull requests merged in 2024-05, with the labels that each got.

#748 Adding system test for provision using Provisioner.NET
  .ci/docker/.env
  .ci/docker/Dockerfile.tpm2provisioner_dotnet
  .ci/docker/docker-compose-system-test.yml
  .ci/setup/container/setup_tpm2provisioner_dotnet.sh
  .ci/system-tests/run_system_tests.sh
  .github/workflows/system_test.yml
Labels: testing, migration

#762 Process SPDM Event EV_EFI_SPDM_FIRMWARE_BLOB
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventData.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventData2.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataDeviceContext.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataHeader.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataHeader2.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataPciContext.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventHeader.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvConstants.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpdmFirmwareBlob.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmHa.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmMeasurement.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmMeasurementBlock.java
Labels: enhancement

#766 updated build to include HIRS_UTILS
  tools/tcg_eventlog_tool/build.gradle
Labels: bug

#753 [#749] ACA setup check
  HIRS_AttestationCAPortal/build.gradle
  build.gradle
  package/linux/aca/aca_check_setup.sh
  package/linux/aca/aca_remove_setup.sh
  package/linux/aca/aca_setup.sh
  package/linux/db/db_create.sh
  package/linux/db/mysql_util.sh
Labels: bug, server, migration

#772 Event processing when no access to vendor-table.json Part 1/2
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureData.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiX509Cert.java
  tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
Labels: bug

#771 V3 boot run debug option
  HIRS_AttestationCAPortal/build.gradle
  package/linux/aca/aca_bootRun.sh
  package/win/aca/aca_bootRun.ps1
Labels: enhancement, server

#769 [#765] Adding ACA Rocky Container for CI System Tests
  .ci/docker/Dockerfile.aca-rocky-ci
  .ci/docker/Dockerfile.tpm2provisioner-dotnet-ci
  .ci/docker/docker-compose-system-test.yml
  .ci/system-tests/run_system_tests.sh
  .github/workflows/system_test.yml
Labels: testing, migration
