Repository nsacyber/HIRS, pull requests merged in 2024-08, with the labels that each got.

#816 Fixes CI test error checking
  .ci/system-tests/container/pc_setup.sh
  .ci/system-tests/container/rim_setup.sh
  .ci/system-tests/run_system_tests.sh
  .ci/system-tests/sys_test_common.sh
  .ci/system-tests/tests/platform_cert_tests.sh
  .ci/system-tests/tests/rim_system_tests.sh
  .github/workflows/system_test.yml
Labels: testing, migration

#819 Add processing for EV_EFI_NOACTION_NvIndexInstance and SPDM Cert Chain data structure
  HIRS_Utils/build.gradle
  HIRS_Utils/src/main/java/hirs/utils/PciIds.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TCGEventLog.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventData.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventData2.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataDeviceContext.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataHeader.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataHeader2.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataPciContext.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataSubHeader.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataSubHeaderCertChain.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventDataSubHeaderSpdmMeasurementBlock.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/DeviceSecurityEventHeader.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiBootServicesApp.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiHandoffTable.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpdmDeviceSecurityEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpecIdEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvNoAction.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvSCrtmVersion.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/NvIndexInstanceEventLogData.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmCertificateChain.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmHa.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmMeasurement.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/spdm/SpdmMeasurementBlock.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiBootOrder.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiBootVariable.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiDevicePath.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiGuid.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSecureBoot.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureData.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
  tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
Labels: enhancement

#831 V3 release README.md updates
  HIRS_Provisioner.NET/README.md
  HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
  HIRS_ProvisionerTPM2/README.md
  README.md
  VERSION
  images/ACA_ValidationReports.png
  images/AcceptanceTest_CIS.png
  images/EndorsementCertificate.png
  images/HIRS_ACA_MAIN_PAGE.png
  images/PlatformCertificate.png
  images/RIM_Certificate.png
  images/TCG_AcceptanceTest.png
  tools/tcg_eventlog_tool/README.md
  tools/tcg_eventlog_tool/VERSION
  tools/tcg_rim_tool/README.md
Labels: documentation, migration
