Repository nsacyber/HIRS, pull requests merged in 2024-01, with the labels that each got.

#659 Added scripts for acceptance testing
  .ci/setup/certs/oem_certs.zip
  scripts/install_hat.ps1
  scripts/remove_hat.ps1
  scripts/start_hat.ps1
Labels: testing

#675 [#674] Updated github actions for unit test artifacts
  .github/workflows/hirs_unit_tests.yml
Labels: migration

#657 [#642] HIRS_AttestationCA spotbug fixes
  HIRS_AttestationCA/config/spotbugs/spotbugs-exclude.xml
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/AbstractEntity.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/tpm/TPM2ProvisionerState.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Certificate.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Device.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/ReferenceManifest.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/SupplyChainValidationSummary.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/IssuedAttestationCertificate.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/CommonCriteriaMeasures.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentIdentifier.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/FIPSLevel.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/PlatformConfiguration.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/TPMSecurityAssertions.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/TPMSpecification.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/URIReference.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/V2/ComponentIdentifierV2.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/PortalInfo.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/TPMInfo.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/report/DeviceInfoReport.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/BaseReferenceManifest.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/ReferenceDigestValue.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/SupportReferenceManifest.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/IdentityClaimProcessor.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/helper/ProvisionUtils.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/SupplyChainValidationService.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/tpm/PcrComposite.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CertificateAttributeScvValidator.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/AppraiserTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/tpm/TPM2ProvisionerStateTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/PlatformCredentialTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/info/PortalInfoTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/info/TPMInfoTest.java
  HIRS_AttestationCAPortal/config/spotbugs/spotbugs-exclude.xml
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageControllerTest.java
Labels: enhancement, Backlog

#658 HIRS_Utils Unit Tests Migration from /hirs/data/persist directory
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/DeviceTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/record/TPMMeasurementRecordTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/report/DeviceInfoReportTest.java
  HIRS_AttestationCA/src/test/resources/VERSION
Labels: migration

#663 Xfer HIRS_Provisioner.NET to main
  .github/workflows/dotnet_provisioner_unit_tests.yml
  HIRS_Provisioner.NET/.editorconfig
  HIRS_Provisioner.NET/hirs.sln
  HIRS_Provisioner.NET/hirs/Directory.Build.targets
  HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
  HIRS_Provisioner.NET/hirs/Resources/Product.wxs
  HIRS_Provisioner.NET/hirs/Resources/ProvisionerTpm2.proto
  HIRS_Provisioner.NET/hirs/appsettings.json
  HIRS_Provisioner.NET/hirs/src/Program.cs
  HIRS_Provisioner.NET/hirs/src/client/Client.cs
  HIRS_Provisioner.NET/hirs/src/client/IHirsAcaClient.cs
  HIRS_Provisioner.NET/hirs/src/client/TbsWrapper.cs
  HIRS_Provisioner.NET/hirs/src/config/CLI.cs
  HIRS_Provisioner.NET/hirs/src/config/ClientExitCodes.cs
  HIRS_Provisioner.NET/hirs/src/config/Settings.cs
  HIRS_Provisioner.NET/hirs/src/deviceInfo/ClassicDeviceInfoCollector.cs
  HIRS_Provisioner.NET/hirs/src/deviceInfo/IHirsDeviceInfoCollector.cs
  HIRS_Provisioner.NET/hirs/src/provisioner/IHirsProvisioner.cs
  HIRS_Provisioner.NET/hirs/src/provisioner/Provisioner.cs
  HIRS_Provisioner.NET/hirs/src/tpm/CommandTpm.cs
  HIRS_Provisioner.NET/hirs/src/tpm/CommandTpmQuoteResponse.cs
  HIRS_Provisioner.NET/hirs/src/tpm/IHirsAcaTpm.cs
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/appsettings.json
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/component_list
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/cert/Mfg.Serial.BASE.cer
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/cert/platform/Mfg.Serial.ver2.base.cer
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/manifest/rim/Mfg.Model.1.rimel
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/manifest/rim/Mfg.Model.1.rimpcr
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/manifest/swidtag/Mfg.Model.1.swidtag
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.base.pem
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.delta.cer
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.rimel
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.rimpcr
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/other/notread.swidtag
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/efi/boot/tcg/pccert/Mfg.Model.ver1.delta.pem
  HIRS_Provisioner.NET/hirsTest/Resources/test/settings_test/event_log
  HIRS_Provisioner.NET/hirsTest/hirsTest.csproj
  HIRS_Provisioner.NET/hirsTest/src/client/ClientTests.cs
  HIRS_Provisioner.NET/hirsTest/src/config/SettingsTests.cs
  HIRS_Provisioner.NET/hirsTest/src/provisioner/ProvisionerTests.cs
  HIRS_Provisioner.NET/tools/pcrextend/pcrextend.csproj
  HIRS_Provisioner.NET/tools/pcrextend/src/Program.cs
  HIRS_Provisioner.NET/tools/pcrextend/src/config/CLI.cs
  HIRS_Provisioner.NET/tools/pcrextend/src/tool/PcrExtendTool.cs
  HIRS_Provisioner.NET/tools/pcrextend/src/tpm/CommandTpmSimulator.cs
Labels: testing, dotnet

#670 BouncyCastle Prerequisite changes
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/EndorsementCredential.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/CommonCriteriaMeasures.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentAddress.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/ComponentIdentifier.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/FIPSLevel.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/PlatformProperty.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/TBBSecurityAssertion.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/URIReference.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/V2/ComponentIdentifierV2.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/attributes/V2/PlatformPropertyV2.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/PciIds.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CertificateAttributeScvValidator.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/certificate/PlatformCredentialTest.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/CertificateDetailsPageControllerTest.java
Labels: bug, refactor

#676 Verison helper update
  HIRS_Utils/src/main/java/hirs/utils/VersionHelper.java
  HIRS_Utils/src/test/java/hirs/utils/VersionHelperTest.java
Labels: enhancement, server

#677 Added VERSION file to /etc/hirs/aca
  HIRS_AttestationCAPortal/build.gradle
  package/scripts/aca/aca_setup.sh
Labels: migration

#681 Unit Test failures as of 1/22
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Device.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/NetworkInfo.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/report/DeviceInfoReport.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/entity/userdefined/DeviceTest.java
Labels: bug, testing

#679 [#642] HIRS_Utils spotbugs fixes
  HIRS_Utils/config/spotbugs/spotbugs-exclude.xml
  HIRS_Utils/src/main/java/hirs/utils/swid/SwidTagConstants.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiGptPartition.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpecIdEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
Labels: enhancement, Backlog

#686 Migration Fixes: HIRS_Structs Unit Tests
  HIRS_Structs/build.gradle
  HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructBuilderTest.java
  HIRS_Structs/src/test/java/hirs/structs/converters/SimpleStructConverterTest.java
Labels: migration

#690 [689] Added 2 unit tests to HIRS_AttestationCA
  HIRS_AttestationCA/build.gradle
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/provision/helper/CredentialManagementHelperTest.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/provision/helper/IssuedCertificateAttributeHelperTest.java
  HIRS_AttestationCA/src/test/resources/certificates/nuc-1/ek_cert_7_byte_header_removed.cer
  HIRS_AttestationCA/src/test/resources/certificates/nuc-1/ek_cert_untouched.cer
  HIRS_AttestationCA/src/test/resources/certificates/platform_certs_2/Intel_pc.pem
Labels: migration
