Repository nsacyber/HIRS, pull requests merged in 2024-06, with the labels that each got.

#781 Adding Platform Cert Tests and RIM System Tests to V3
  .ci/system-tests/container/rim_setup.sh
  .ci/system-tests/run_system_tests.sh
  .ci/system-tests/setup_system_tests.sh
  .ci/system-tests/tests/platform_cert_tests.sh
  .ci/system-tests/tests/rim_system_tests.sh
  .github/workflows/system_test.yml
Labels: testing, migration

#778 Event processing when no access to vendor-table.json Part 2
  HIRS_AttestationCAPortal/build.gradle
  HIRS_Utils/src/main/java/hirs/utils/JsonUtils.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TCGEventLog.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpdmFirmwareBlob.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiConstants.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiGuid.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
  HIRS_Utils/src/main/resources/vendor-table.json
  package/linux/aca/aca_setup.sh
  package/win/aca/aca_setup.ps1
  tools/tcg_eventlog_tool/src/main/java/hirs/tcg_eventlog/Main.java
Labels: enhancement

#786 Changed DB lookup of RIM EL objects, added null checks to Device.toString
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/manager/SupplyChainValidationSummaryRepository.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Device.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/SupplyChainValidation.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/rim/EventLogMeasurements.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/SupplyChainValidationService.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/FirmwareScvValidator.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java
  HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
Labels: bug

#792 Add SPDM Events Part 2
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/TpmPcrEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvConstants.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/events/EvEfiSpdmDeviceSecurityEvent.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java
  HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiVariable.java
Labels: enhancement
