Repository nsacyber/HIRS, pull requests merged in 2025-05, with the labels that each got.

#931 [#821] HIRS Attestation ACA Should Download ACA Certificate chain
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/RestfulAttestationCertificateAuthority.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/CertificateService.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/PersistenceJPAConfig.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/TrustChainCertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/CertificateStringMapBuilder.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/utils/ControllerPagesUtils.java
  HIRS_AttestationCAPortal/src/main/resources/application.properties
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/trust-chain.jsp
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/PageControllerTest.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/PageTestConfiguration.java
  HIRS_AttestationCAPortal/src/test/java/hirs/attestationca/portal/page/controllers/TrustChainManagementPageControllerTest.java
Labels: enhancement

#930 Holder labels updated
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/certificate-details.jsp
Labels: server

#933 [#925] Allow User To Download ACA Log Off Of Help Page
  HIRS_AttestationCAPortal/build.gradle
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/HIRSApplication.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/Page.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/HIRSLogController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/LombokLoggingController.java
  HIRS_AttestationCAPortal/src/main/resources/application.properties
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/help.jsp
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/index.jsp
  HIRS_AttestationCAPortal/src/main/webapp/common/common.css
  gradle/versions.toml
Labels: new feature

#932 [#922] Fixed 404 Error When Downloading Validation Report
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/service/ValidationSummaryReportsService.java
  HIRS_AttestationCAPortal/src/main/webapp/WEB-INF/jsp/validation-reports.jsp
Labels: bug
