Repository nsacyber/HIRS, pull requests merged in 2025-08, with the labels that each got.

#983 [#979]: Lengthen Certificate Bytes Column Definition
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/Certificate.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/certificate/CertificateVariables.java
Labels: server

#993 Empty, null, Unknown, Not Specified equivalence in component serial and revision
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/entity/userdefined/info/ComponentInfo.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/CertificateAttributeScvValidator.java
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/validation/SupplyChainCredentialValidator.java
  HIRS_AttestationCA/src/test/java/hirs/attestationca/persist/validation/SupplyChainCredentialValidatorTest.java
  HIRS_AttestationCA/src/test/resources/hirs/validation/ci_profiles/default/laptop.default.1.base.cer
  HIRS_AttestationCA/src/test/resources/hirs/validation/ci_profiles/default/laptop_default_hw.json
Labels: enhancement, server

#969 [#968] Addressing RIM certificate validation issues
  HIRS_Utils/src/main/java/hirs/utils/rim/ReferenceManifestValidator.java
  HIRS_Utils/src/main/java/hirs/utils/swid/SwidTagConstants.java
Labels: bug
