Repository nsacyber/HIRS, pull requests merged in 2025-04, with the labels that each got.

#914 Provisioner to use updated registry libraries
  HIRS_Provisioner.NET/hirs/HIRS_Provisioner.NET.csproj
Labels: enhancement

#916 Take only first cert in multi part PEM
  .github/workflows/dotnet_provisioner_unit_tests.yml
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/util/CredentialHelper.java
Labels: bug

#910 [#909] Refactor @RequestMapping to Specific @GetMapping and @PostMapping Annotations
  HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/RestfulAttestationCertificateAuthority.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/CertificatePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PolicyPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ReferenceManifestPageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java
  HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java
Labels: refactor

#921 docker login action v4 does not exist yet
  .github/workflows/create_aca_images.yml
Labels: bug
